update api implementation and generate client
Galactus-Player/roomservice pull request #5
Opened 2020-10-20 05:59 UTC by Rjected

## Major changes
  - generated client
  - updated dockerfile version
  - create tests and benchmarks

2020-10-20 18:00 UTC, Rjected commented on galactuslib/api_room_service_test.go
> +}
Example of functioning service use in tests

2020-10-20 22:43 UTC, lukeyeh requested changes
some very small nits, but LGTM

2020-10-20 22:43 UTC, lukeyeh commented on cmd/roomservice/main.go
> +	log.Printf("Server started")
Maybe put this log after the server has started (line 27) or change the message to "Server starting" instead?

2020-10-20 22:43 UTC, lukeyeh commented on README.md
>  To run the server in a docker container
Tests already show how to make calls to server, but maybe add a small snippet on how to do that here.

2020-10-20 23:08 UTC, lukeyeh commented on README.md
>  To run the server in a docker container
Or if you're lazy just add a link to the tests.

2020-10-21 02:36 UTC, lukeyeh commented
LGTM

2020-10-21 18:56 UTC, merged